In [8]:
import numpy as np
import time

from q3dfm.helper_mat import helper_mat

In [2]:
np.full((2, 2, 3), np.nan)

array([[[nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan]]])

In [4]:
np.kron(np.ones(2) / 2, np.eye(2))

array([[0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5]])

In [6]:
H = np.random.rand(5, 4)
HJ = np.dot(H[1, :], np.kron(np.ones(30) / 30, np.eye(4)))

In [7]:
HJ.shape

(120,)

In [11]:
H = np.ones(2)

In [14]:
J = helper_mat(2, False, 2, 4)
J

array([[0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5]])

In [15]:
H @ J

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
np.dot(
    H,
    np.kron(
        np.concatenate([np.arange(1, 2 + 1), np.arange(2 - 1, 0, -1)]) / 2,
        np.eye(2),
    ),
)

In [16]:
np.dot(
    H,
    np.kron(
        np.ones(2) / 2,
        np.eye(2),
    ),
)

array([0.5, 0.5, 0.5, 0.5])