In [1]:
import numpy as np
import time

from q3dfm.helper_mat import helper_mat

In [2]:
np.full((2, 2, 3), np.nan)

array([[[nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan]]])

In [3]:
np.kron(np.ones(2) / 2, np.eye(2))

array([[0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5]])

In [4]:
H = np.random.rand(5, 4)
HJ = np.dot(H[1, :], np.kron(np.ones(30) / 30, np.eye(4)))

In [5]:
HJ.shape

(120,)

In [11]:
H = np.ones(2)

In [14]:
J = helper_mat(2, False, 2, 4)
J

array([[0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5]])

In [15]:
H @ J

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
np.dot(
    H,
    np.kron(
        np.concatenate([np.arange(1, 2 + 1), np.arange(2 - 1, 0, -1)]) / 2,
        np.eye(2),
    ),
)

In [16]:
np.dot(
    H,
    np.kron(
        np.ones(2) / 2,
        np.eye(2),
    ),
)

array([0.5, 0.5, 0.5, 0.5])

In [4]:
# Original comp_form function
def comp_form_original(B):
    m, p = B.shape
    A = np.zeros((m * p, m * p))
    A[:m, :p] = B  # Fill the top-left block with B

    for i in range(m):
        A[i + m : (i + m * (p - 1)), i] = np.eye(
            m
        )  # Fill the sub-diagonal blocks

    return A


# One-liner comp_form function
def comp_form_oneliner(B):
    return np.block(
        [
            [B] + [np.eye(B.shape[0])] * (B.shape[1] - 1),
            [np.zeros((B.shape[0] * (B.shape[1] - 1), B.shape[1]))],
        ]
    )


# Test code
B = np.random.rand(3, 2)  # Random matrix B for testing

#A_original = comp_form_original(B)
A_oneliner = comp_form_oneliner(B)

# Test if both methods return the same matrix
if np.allclose(A_original, A_oneliner):
    print("Both methods return the same matrix!")
else:
    print("The matrices are different.")

# Optionally, print the matrices for comparison
print("Original method output:\n", A_original)
print("One-liner method output:\n", A_oneliner)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [1]:
import numpy as np
from scipy.sparse.linalg import eigs

# Simulation de données
np.random.seed(0)
xTemp = np.random.randn(100, 5)  # Matrice 100x5
lblock = np.array([True, False, True, False, True])  # Masque logique

# Calcul de la matrice de covariance
cov_matrix = np.cov(xTemp[:, lblock], rowvar=False)

# Calcul de la plus grande valeur propre et vecteur propre
eigenvalue, eigenvector = eigs(cov_matrix, k=1, which="LM")

# Affichage des résultats
print("Valeur propre maximale :", eigenvalue)
print("Vecteur propre associé :", eigenvector)

Valeur propre maximale : [1.16852985+0.j]
Vecteur propre associé : [[-0.69858982+0.j]
 [ 0.57736961+0.j]
 [ 0.42263058+0.j]]


In [33]:
import numpy as np


def test_replace_nan():
    # Créer une matrice X avec des valeurs NaN
    X = np.array([[1, 2, np.nan], [4, np.nan, 6], [np.nan, 8, 9]], dtype=float)

    # Afficher la matrice avant remplacement
    print("Matrice avant remplacement des NaN :")
    print(X)

    # Compter le nombre de NaN avant remplacement
    nan_count_before = np.isnan(X).sum()
    print(f"Nombre de NaN avant remplacement : {nan_count_before}")

    # Remplacer les NaN par des valeurs tirées de N(0,1)
    X[np.isnan(X)] = np.random.randn(np.isnan(X).sum())

    # Afficher la matrice après remplacement
    print("\nMatrice après remplacement des NaN :")
    print(X)

    # Compter le nombre de NaN après remplacement (devrait être 0)
    nan_count_after = np.isnan(X).sum()
    print(f"Nombre de NaN après remplacement : {nan_count_after}")

    # Vérifier que tous les NaN ont été remplacés
    assert nan_count_after == 0, "Tous les NaN n'ont pas été remplacés."
    print(
        "\nTest réussi : Tous les NaN ont été remplacés par des valeurs aléatoires."
    )


# Exécuter le test
test_replace_nan()

Matrice avant remplacement des NaN :
[[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]
Nombre de NaN avant remplacement : 3

Matrice après remplacement des NaN :
[[ 1.          2.         -1.40042436]
 [ 4.          1.82445151  6.        ]
 [ 1.36790865  8.          9.        ]]
Nombre de NaN après remplacement : 0

Test réussi : Tous les NaN ont été remplacés par des valeurs aléatoires.


In [11]:
m, p = 1, 3

B = np.random.rand(m, m*p)

A = np.vstack(
    [
        B,
        np.hstack([np.eye(m * (p - 1)), np.zeros((m * (p - 1), m))]),
    ]
)

A 

array([[0.36862928, 0.76161883, 0.63177529],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ]])

In [7]:
import numpy as np

# Fonction pour générer Z à partir de z
stack_obs = lambda z, p: np.hstack(
    [z[p - i - 1: -i - 1, :] for i in range(p)]
)


# Test
def test_stack_obs():
    # Exemple de données
    z = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
    p = 2  # Nombre de lags

    # Résultat attendu
    expected_Z = np.array([[3, 4], [5, 6]])

    # Appel de la fonction
    result = stack_obs(z, p)

    # Vérification
    assert np.array_equal(
        result, expected_Z
    ), f"Expected {expected_Z}, but got {result}"


# Exécution du test
test_stack_obs()
print("Test passed!")

AssertionError: Expected [[3 4]
 [5 6]], but got [[3 4 1 2]
 [5 6 3 4]]

In [8]:
z = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
p = 2  # Nombre de lags

    # Résultat attendu
expected_Z = np.array([[3, 4], [5, 6]])

    # Appel de la fonction
result = stack_obs(z, p)

In [4]:
z.shape

(4, 2)

In [3]:
result

array([[3, 4, 1, 2],
       [5, 6, 3, 4]])